# The basic structure was taken from a Scala Github workflow:
# [1] Github Actions Contributors. (2021) Scala.yml. [Code] 
# https://github.com/chloe-blankers/seng371-milestone1/new/main?filename=.github%2Fworkflows%2Fscala.yml&workflow_template=scala
#
# The syntax for deleting a file is provided through the following:
# [2] tj-actions. (2022). README.md. [Code] 
# https://github.com/tj-actions/changed-files
#
# The syntax for the labeler is provided through the following:
# [3] Github Actions Contributors. (2022) README.md. [Code].
# https://github.com/actions/labeler
#
# Some Information on Code Owners is provided through the following:
# [4] Github Doc Contributors. "About Code Owners." docs.github.com.
# Available: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners 
#
# Some Information on Strategy and Matrices:
# [5] Github Contributors. "Using a build matrix for your jobs." docs.github.com.
# Available: https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs
#

name: Compile and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check_for_delete:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
          
    - name: Determine if required files were changed.
      id: required-files-changed
      uses: tj-actions/changed-files@v16
      with:
        files: |
          build.sbt
          project/plugins.sbt

    - if: steps.required-files-changed.outputs.any_deleted == 'true'
      name: Prevent submission when sbt files were deleted
      run: |
        echo "[FAILURE]: The necessary file `build.sbt` was deleted.";
        exit 1

    - if: steps.required-files-changed.outputs.any_modified == 'true'
      name: Add Warning Label when sbt files were changed
      uses: actions/labeler@v3
      with: 
        repo-token: "${{ secrets.GITHUB_TOKEN }}" 

  compile:
    needs: check_for_delete
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [11, 16, 17]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK version
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
    - name: Compile Program
      run: sbt compile

  test:
    needs: compile
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run tests
      run: sbt test
