# The basic structure was taken from a Scala Github workflow:
# [1] Github Actions Contributors. (2021) Scala.yml. [Code] 
# https://github.com/chloe-blankers/seng371-milestone1/new/main?filename=.github%2Fworkflows%2Fscala.yml&workflow_template=scala
#
# The syntax for deleting a file is provided through the followingL
# [2] tj-actions. (2022). README.md. [Code] 
# https://github.com/tj-actions/changed-files

name: Compile and Test CI

on:
  push:
    branches: [ main, protect_build_sbt_test ]
  pull_request:
    branches: [ main, protect_build_sbt_test ]

jobs:

  check_for_delete:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Determine if required files were changed.
      id: required-files-changed
      uses: tj-actions/changed-files@v16
      with:
        files: |
          build.sbt
          project/plugins.sbt

    - if: steps.required-files-changed.outputs.any_deleted == 'true'
      name: Prevent submission when sbt files were deleted
      run: |
        echo "[FAILURE]: The necessary file `build.sbt` was deleted.";
        exit 1

    - if: steps.required-files-changed.outputs.any_modified == 'true'
      name: Add Warning Label when sbt files were changed
      uses: actions/labeler@v3
      with: 
        repo-token: "${{ secrets.GITHUB_TOKEN }}" 

  compile:
    needs: check_for_delete
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8, 11, 14]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compile Program
      run: sbt compile

  test:
    needs: compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run tests
      run: sbt test
