#The following sources were used:
# https://github.com/marketplace/actions/issue-timer

name: Label Issues 
on: 

  workflow_dispatch:
  project_card:
    types: [created, moved, coverted, edited]
  push:
    branches: [main]

jobs:
  issues_r:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.8'
    - name: Adding label after 30 mins 
      uses: isethi/issue-timer@main
      with:
        PROJECT_ID: 1
        TIME_IN_MINUTES: 30
        LABEL_NAME: time to review 
        
  #pr:
    
