# The following sources were used:
# https://github.com/marketplace/actions/issue-timer
# https://github.com/technote-space/auto-card-labeler

name: Label All Cards in Project Board and Unattended Issues 
on: 

  workflow_dispatch:
  project_card:
    types: [created, moved]
  push:
    branches: [main]

jobs:

  add_progress_labels:
    name: Card Label 
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/auto-card-labeler@v2
      
  issues_r:
    name: Finding issues in project board
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.8'
    - name: Adding label after 45 mins 
      uses: isethi/issue-timer@main
      with:
        PROJECT_ID: 1
        TIME_IN_MINUTES: 45
        LABEL_NAME: 'time to review'






  
    
