# Resource used:
# https://github.com/marketplace/actions/label-remover


name: Removing Closed Pull Request and Issues Labels

on:
  pull_request:
    types: [closed, merged]
  issues:
    types: [closed]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rogerluan/label-remover@v1.0.1
        with:
          github_token: ${{ secrets.github_token }}
