# The basic structure of the steps were taken from:
# https://github.com/marketplace/actions/slack-notify 

name: Compile/Test Fail Notification

on:
  workflow_run:
    workflows: [Compile and Test CI]
    types: [completed]

jobs:
  on-failure:
    name: Workflow Fail
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: actions/checkout@v2
    - name: Slack Workflow Fail Notification 
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Compile and Test workflow failed'
        SLACK_TITLE: Failed!!!
        SLACK_COLOR: ED1D24
        SLACK_ICON: repository
        SLACK_ICON_EMOJI: ':fire:'
        
